

theme: jekyll-theme-minimal
title: Sahil Karawade 
description: Interested in Algebraic geometry and Arithmetic Geometry
text: <a href='mailto:sahilkarawade99@gmail.com'> `sahilkarawade99@gmail.com` </a>
