theme: jekyll-theme-minimal
title: Sahil Karawade
description:
  <p align="justify">
  Interested in Algebraic Geometry more specifically Arithmetic Geometry and Moduli Spaces.
  <br><br>
logo: "C:\Users\Sahil Karawade\Downloads\My project.jpg"
github:
is_project_page: false
