theme: jekyll-theme-minimal
title: Sahil Karawade
logo: "/images/20220510_15215412_edited.jpg"
author:
  name: Sahil Karawade
  email: sahilkarawade99@gmail.com

url: https://sahil-karawade.github.io/
description:
  <p align="justify">
  Mainly interested in Algebraic Geometry and allied areas
  <br><br>

url:
    - text: About Me
      url: /about/
  

github:
is_project_page: false

plugins:
  - jekyll-sitemap
