theme: jekyll-theme-minimal
title: Sahil Karawade
logo: "/images/20220510_15215412_edited.jpg"
description:
  <p align="justify">
  Interested in Algebraic Geometry more specifically Arithmetic Geometry and Moduli Spaces.
  <br><br>

github:
is_project_page: false
