theme: jekyll-theme-minimal
title: Sahil Karawade
logo: "/images/My project (1).jpg"
email: "sahilkarawade99@gmail.com"
url: https://sahil-karawade.github.io/
description:
  <p align="justify">
  Mainly interested in Algebraic Geometry and allied areas
  <br><br>
  

github:
is_project_page: false
