theme: jekyll-theme-minimal
title: Sahil Karawade
description:
  <p align="justify">
  Interested in Algebraic Geometry more specifically Arithmetic Geometry and Moduli Spaces.
  <br><br>
logo: C:\Users\Sahil Karawade\OneDrive\Pictures\Saved Pictures\20220510_1521541.jpg

github:
is_project_page: false
