theme: jekyll-theme-minimal
title: Sahil Karawade
logo: "/images/My project (1).jpg"
author:
  name: Sahil Karawade
  email: sahilkarawade99@gmail.com


description:
  <p align="justify">
  Mainly interested in Algebraic Geometry and allied areas
  <br><br>

url:
    - text: About Me
      url: /about/
  

github:
is_project_page: false

url: https://sahil-karawade.github.io/
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
